public class Class1 {
    public static void main(String[] args){
        Integer i,j;
        i=10;
        System.debug(j=i+i*i+j);
    }
    public static void dupe1(){
        new pull request checking
    }
    public static void dupe2(){
        
    }
    public static void dupe3(){
        
    }
    public static void dupe1(){
        
    }
    public static void dupe2(){
        
    }
    public static void dupe3(){
        
    }
}
